/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DESKTOP-TPC6SO4
 */
public class frmPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla1
     */
    public frmPantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new FondoPanel();
        btnIngresar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuIngresar = new javax.swing.JMenu();
        menuIngresarAdministrador = new javax.swing.JMenuItem();
        menuIngresarVendedor = new javax.swing.JMenuItem();
        menuOtrosUsuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuRegistrar = new javax.swing.JMenu();
        menuRegistrarAdministrador = new javax.swing.JMenuItem();
        menuRegistrarVendedor = new javax.swing.JMenuItem();
        menuRegistrarOtrosUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTA DE VEHÍCULOS");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setForeground(new java.awt.Color(204, 255, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnIngresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IniciarSesion_48.png"))); // NOI18N
        btnIngresar.setText("Iniciar Sesión");
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IniciarSesion_48.png"))); // NOI18N
        btnIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IniciarSesion_64.png"))); // NOI18N
        btnIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 35, 0, 0);
        jPanel2.add(btnIngresar, gridBagConstraints);

        btnRegistrarse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse_48.png"))); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarse.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse_48.png"))); // NOI18N
        btnRegistrarse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse_64.png"))); // NOI18N
        btnRegistrarse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 10, 0, 42);
        jPanel2.add(btnRegistrarse, gridBagConstraints);

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir_48.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir_48.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir_64.png"))); // NOI18N
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 100, 17, 0);
        jPanel2.add(btnSalir, gridBagConstraints);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Usuarios");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu1.add(jSeparator1);

        menuIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IniciarSesion_32.png"))); // NOI18N
        menuIngresar.setText("Ingresar");

        menuIngresarAdministrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuIngresarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioAdmin_32.png"))); // NOI18N
        menuIngresarAdministrador.setText("Administrador");
        menuIngresarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarAdministradorActionPerformed(evt);
            }
        });
        menuIngresar.add(menuIngresarAdministrador);

        menuIngresarVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuIngresarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioVendedor_32.png"))); // NOI18N
        menuIngresarVendedor.setText("Vendedor");
        menuIngresarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarVendedorActionPerformed(evt);
            }
        });
        menuIngresar.add(menuIngresarVendedor);

        menuOtrosUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOtrosUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioOtro_32.png"))); // NOI18N
        menuOtrosUsuarios.setText("Otros");
        menuOtrosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtrosUsuariosActionPerformed(evt);
            }
        });
        menuIngresar.add(menuOtrosUsuarios);

        jMenu1.add(menuIngresar);
        jMenu1.add(jSeparator2);

        menuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse_32.png"))); // NOI18N
        menuRegistrar.setText("Registrarse");

        menuRegistrarAdministrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuRegistrarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioAdmin_32.png"))); // NOI18N
        menuRegistrarAdministrador.setText("Administrador");
        menuRegistrarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarAdministradorActionPerformed(evt);
            }
        });
        menuRegistrar.add(menuRegistrarAdministrador);

        menuRegistrarVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuRegistrarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioVendedor_32.png"))); // NOI18N
        menuRegistrarVendedor.setText("Vendedores");
        menuRegistrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarVendedorActionPerformed(evt);
            }
        });
        menuRegistrar.add(menuRegistrarVendedor);

        menuRegistrarOtrosUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuRegistrarOtrosUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioOtro_32.png"))); // NOI18N
        menuRegistrarOtrosUsuarios.setText("Otros");
        menuRegistrarOtrosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarOtrosUsuariosActionPerformed(evt);
            }
        });
        menuRegistrar.add(menuRegistrarOtrosUsuarios);

        jMenu1.add(menuRegistrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Salir");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir_32.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(menuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salir(){
        JOptionPane.showMessageDialog(null, "******************************GRACIAS POR USAR NUESTRO SISTEMA******************************"
                                        + "\nPROGRAMA CREADO POR JHON JAIRO MANZABA GUARAMA");
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Seguro desea salir del programa");
        
        if (opcion==JOptionPane.OK_OPTION) {
            salir();
            System.exit(0);
        }             
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuIngresarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarVendedorActionPerformed
        frmLogin logVendedor = new frmLogin();
        logVendedor.jcbTipoDeUsuario.setSelectedIndex(1);
        logVendedor.jcbTipoDeUsuario.setEnabled(false);
        logVendedor.show(true);
        this.show(false);
    }//GEN-LAST:event_menuIngresarVendedorActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        salir();
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        frmRegistroUsuarios registro = new frmRegistroUsuarios();
        registro.show(true);
        this.show(false);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void menuRegistrarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarAdministradorActionPerformed
        frmRegistroUsuarios registroAdm = new frmRegistroUsuarios();
        registroAdm.jcbTipoDeUsuario.setSelectedIndex(0);
        registroAdm.jcbTipoDeUsuario.setEnabled(false);
        registroAdm.show(true);
        this.show(false);
    }//GEN-LAST:event_menuRegistrarAdministradorActionPerformed

    private void menuRegistrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarVendedorActionPerformed
        frmRegistroUsuarios registroVendedores = new frmRegistroUsuarios();
        registroVendedores.jcbTipoDeUsuario.setSelectedIndex(1);
        registroVendedores.jcbTipoDeUsuario.setEnabled(false);
        registroVendedores.show(true);
        this.show(false);
    }//GEN-LAST:event_menuRegistrarVendedorActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        frmLogin login = new frmLogin();
        login.show(true);
        this.show(false);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void menuIngresarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarAdministradorActionPerformed
        frmLogin logAdm = new frmLogin();
        logAdm.jcbTipoDeUsuario.setSelectedIndex(0);
        logAdm.jcbTipoDeUsuario.setEnabled(false);
        logAdm.show(true);
        this.show(false);
    }//GEN-LAST:event_menuIngresarAdministradorActionPerformed

    private void menuOtrosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtrosUsuariosActionPerformed
        frmLogin logOtrosUsuarios = new frmLogin();
        logOtrosUsuarios.jcbTipoDeUsuario.setSelectedIndex(2);
        logOtrosUsuarios.jcbTipoDeUsuario.setEnabled(false);
        logOtrosUsuarios.show(true);
        this.show(false);
    }//GEN-LAST:event_menuOtrosUsuariosActionPerformed

    private void menuRegistrarOtrosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarOtrosUsuariosActionPerformed
        frmRegistroUsuarios registroOtrosUser = new frmRegistroUsuarios();
        registroOtrosUser.jcbTipoDeUsuario.setSelectedIndex(2);
        registroOtrosUser.jcbTipoDeUsuario.setEnabled(false);
        registroOtrosUser.show(true);
        this.show(false);
    }//GEN-LAST:event_menuRegistrarOtrosUsuariosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuIngresar;
    private javax.swing.JMenuItem menuIngresarAdministrador;
    private javax.swing.JMenuItem menuIngresarVendedor;
    private javax.swing.JMenuItem menuOtrosUsuarios;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JMenuItem menuRegistrarAdministrador;
    private javax.swing.JMenuItem menuRegistrarOtrosUsuarios;
    private javax.swing.JMenuItem menuRegistrarVendedor;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
